{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret  # ✅ Use the helper function

  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # ← Create before everything
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc }}
  password: {{ .Values.auth.password | b64enc }}
  database: {{ .Values.auth.database | b64enc }}
{{- end }}
