apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: els-lmsclient-feature-branches
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - branch: feature/autodeploy
        name: feature-autodeploy
      - branch: feature/add-new-api
        name: feature-add-new-api
      - branch: major/helm_lms
        name: major-helm-lms

  template:
    metadata:
      name: 'els-lmsclient-{{branch}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/hcmuleva/els-demo.git
        targetRevision: '{{branch}}'
        path: helm/charts/els-lmsclient
        helm:
          valueFiles:
            - values_dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: els-lms-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m