apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: els-lmsserver-feature-branches
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/hcmuleva/els-demo.git
      revision: HEAD
      directories:
      - path: helm/charts/els-lmsserver
      branches:
      - 'feature/*'
      - 'bug/*'
      - 'patch/*'
      - 'minor/*'
      - 'major/*'

  template:
    metadata:
      name: 'els-lmsserver-{{branch}}-{{path.basename}}'
      namespace: argocd
      labels:
        app: els-lmsserver
        environment: dev
        branch: '{{branch}}'
    spec:
      project: default
      
      source:
        repoURL: https://github.com/hcmuleva/els-demo.git
        targetRevision: '{{branch}}'
        path: helm/charts/els-lmsserver
        helm:
          valueFiles:
            - values_dev.yaml
      
      destination:
        server: https://kubernetes.default.svc
        namespace: els-lms-dev
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      
      # Health checks
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
