apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: client-prod
  namespace: argocd
spec:
  description: Client Production Environment
  sourceRepos:
    - 'https://github.com/hcmuleva/els-release.git'
  destinations:
    - namespace: client-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
