apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: server-prod
  namespace: argocd
spec:
  description: Server Production Environment
  sourceRepos:
    - 'https://github.com/hcmuleva/els-release.git'
  destinations:
    - namespace: server-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
