apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elslmsclient.name }}-service
  labels:
    app: {{ .Values.elslmsclient.name }}
spec:
  selector:
    app: {{ .Values.elslmsclient.name }}
  ports:
    - port: {{ .Values.elslmsclient.servicePort }}
      targetPort: {{ .Values.elslmsclient.containerPort }}
