apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: strapi-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: els-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: strapi-service
            port:
              number: 80
