{{- if .Values.elslmsserver.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.elslmsserver.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # optional â€” can remove if DB is external
  labels:
    app: {{ .Values.elslmsserver.name }}
spec:
  replicas: {{ .Values.elslmsserver.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.elslmsserver.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.elslmsserver.name }}
    spec:
      containers:
        - name: {{ .Values.elslmsserver.name }}
          image: "{{ .Values.elslmsserver.image }}:{{ .Values.elslmsserver.tag }}"
          imagePullPolicy: {{ .Values.elslmsserver.imagePullPolicy }}
          env:
          {{- range $key, $value := .Values.elslmsserver.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          ports:
            - containerPort: {{ .Values.elslmsserver.containerPort }}
          readinessProbe:
            httpGet:
              path: /_health
              port: {{ .Values.elslmsserver.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /_health
              port: {{ .Values.elslmsserver.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 20
{{- end }}
