{{- if .Values.elslmsserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elslmsserver.name }}-service
  labels:
    app: {{ .Values.elslmsserver.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.elslmsserver.name }}
  ports:
    - port: {{ .Values.elslmsserver.servicePort }}
      targetPort: {{ .Values.elslmsserver.containerPort }}
{{- end }}
