apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: els-client-dev
  namespace: argocd
spec:
  project: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    repoURL: https://github.com/hcmuleva/els-release.git
    targetRevision: dev
    path: fullstack_level3/devops/helm/client
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: ingress.hosts[0].host
        value: dev.els-client.local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

