apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strapi-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: strapi-dev
  source:
    repoURL: https://github.com/hcmuleva/els-release.git
    targetRevision: dev
    path: release/devops/level-3/helm
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: env.NODE_ENV
        value: development
      - name: ingress.hosts[0].host
        value: dev.els-api.local
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      
