elslmsserver:
  enabled: true
  name: els-lmsserver
  image: harishdell/els-lmsserver
  tag: "1.13.11-pr39"
  imagePullPolicy: IfNotPresent
  containerPort: 1337
  servicePort: 1337
  
  env:
    HOST: "0.0.0.0"
    PORT: "1337"
    DATABASE_HOST: "postgres-postgres.db.svc.cluster.local"  # âœ… Correct service name
    DATABASE_CLIENT: "postgres"
    DATABASE_PORT: "5432"
    DATABASE_NAME: "elslmsdev"
    DATABASE_USERNAME: "postgres"
    DATABASE_PASSWORD: "postgres"
    PUBLIC_URL: "http://els-lmsserver.local"
    ALLOWED_HOSTS: "localhost,127.0.0.1,els-lmsserver.local,elslms.local,els-lms-api.local,els-lms-ui.local"


ingress:
  enabled: true
  host: "dev-els-lmsserver.local"
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls: []