elslmsserver:
  enabled: true
  name: els-lmsserver
  image: harishdell/els-lmsserver
  tag: "1.13.11-feature-autodeploy-df5e3a44"
  imagePullPolicy: IfNotPresent
  containerPort: 1337
  servicePort: 1337
  
  env:
    HOST: "0.0.0.0"
    PORT: "1337"
    DATABASE_HOST: "postgres-postgres.db.svc.cluster.local"  # âœ… Correct service name
    DATABASE_CLIENT: "postgres"
    DATABASE_PORT: "5432"
    DATABASE_NAME: "elslmsdev"
    DATABASE_USERNAME: "postgres"
    DATABASE_PASSWORD: "postgres"
    APP_KEYS: B0dHK07fL+o6ha4Y7T/dBg==,KNHRAcYqezZ9i/4NAKaKrA==,tCWCEff/xF1M8nuTA6KOCg==,98aVEzN4mFYKK/gVuFWFMQ==
    API_TOKEN_SALT: UZbp4y93fwS8vaxZ9wPqgA==
    ADMIN_JWT_SECRET: uxNppuQFOdZl4jeFiY3KJg==
    TRANSFER_TOKEN_SALT: lxHiqPp4tfxP8roPp7gOOQ==
    ENCRYPTION_KEY: 9Y+SbEFrJWHS7JzaXD/q3Q==
    PUBLIC_URL: "http://dev-els-lmsserver.local"
    ALLOWED_HOSTS: "localhost,127.0.0.1,dev-els-lmsserver.local,elslms.local,els-lms-api.local,els-lms-ui.local"

ingress:
  enabled: true
  host: "dev-els-lmsserver.local"
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls: []