# ===========================================
# Common configuration
# ===========================================
replicaCount: 1
imagePullPolicy: IfNotPresent

# ===========================================
# React App configuration
# ===========================================
elslmsclient:
  name: els-lmsclient
  image: harishdell/els-lmsclient
<<<<<<< HEAD
  tag: "1.1"
=======
  tag: "1.13.8-pr32"
>>>>>>> d6c2290954c4dfe1d923f8975b3a513d618310a5
  containerPort: 80
  servicePort: 80
  env:
    REACT_APP_API_URL: http://els-lmsserver.local

# ===========================================
# Ingress configuration
# ===========================================
ingress:
  enabled: true
  name: els-lmsclient-ingress
  host: els-lmsclient.local
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  paths:
    - path: /
      pathType: Prefix
      service: els-lmsclient-service
      port: 80