apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: els-lmsserver-qa
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL:  https://github.com/hcmuleva/els-demo.git
    targetRevision: main
    path: helm/charts/els-lmsserver
    helm:
      valueFiles:
        - values_qa.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: els-lms-qa
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true