# argocd/applications/els-lmsclient-qa.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: els-lmsclient-qa
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/your-org/your-repo.git
    targetRevision: main
    path: helm/charts/els-lmsclient
    helm:
      valueFiles:
        - values_qa.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: els-lms-qa
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
