apiVersion: v1
kind: Service
metadata:
  name: flask-lab1
spec:
  selector:
    app: flask-lab1
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
