services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strapi-cms
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: development
    volumes:
      - .:/opt/app
      - node_modules:/opt/app/node_modules
      - strapi_db:/opt/app/.tmp
    restart: unless-stopped

volumes:
  node_modules:
  strapi_db:
