---
# Source: flask-lab1/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-lab1
spec:
  selector:
    app: flask-lab1
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP
---
# Source: flask-lab1/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-lab1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-lab1
  template:
    metadata:
      labels:
        app: flask-lab1
    spec:
      containers:
        - name: flask-lab1
          image: "flask-lab1:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
# Source: flask-lab1/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-lab1
  annotations:
    {}
spec:
  ingressClassName: nginx
  rules:
    - host: flask-lab1.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-lab1
                port:
                  number: 80
