image:
  repository: harishdell/karate
  tag: "1.0"
  pullPolicy: IfNotPresent

karate:
  env: dev
  options: "--tags ~@ignore"
  
test:
  url: "http://els-lmsserver-dev.els-lms-dev.svc.cluster.local:1337"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

backoffLimit: 1
persistence:
  size: "1Gi"